### ISSUE TITLE
Using this to add sidecars to ECS tasks that are not part of a service

### ISSUE THREAD

**Issue by SamStephens** [cdklabs/cdk-ecs-service-extensions#134]
My understanding is that this package is intended way that CDK users add sidecars such as the Cloudwatch Agent or AWS X-Ray to their ECS tasks.

However, the entire approach this package takes is predicated on ECS tasks being managed as part of an ECS service, unless I've misunderstood the constructs provided.

However there are use cases for running ECS tasks outside of an ECS service. For example, I have a Step Functions State Machine that uses [the ecs:runTask](https://docs.aws.amazon.com/step-functions/latest/dg/connect-ecs.html) integration to directly run ECS tasks within a Cluster, but without any Service being involved?

Is there a supported pattern for attaching Sidecars to Tasks like these using the CDK?

**Comment by bvtujo** [comment]
This isn't really in scope for this module, unfortunately--the extensions are specifically designed to help manage ECS Services. I can see the use case for a modular way of modifying task definitions, and I'll try to surface it to the relevant teams, but we don't have plans to extract the task definition modifications here. You might be able to do something like this, though:
1. use the extensions to create a service with your desired task definition
2. create a new stack using that task definition via `cdk.Stack.of(service.taskDefinition)`
3. Add other resources for your one-off task/state machine to that stack
4. only deploy the new stack, not the original.
