### ISSUE TITLE
Container requires a single trafficPort, which is a problem for services that listen on no port or many ports

### ISSUE THREAD

**Issue by SamStephens** [cdklabs/cdk-ecs-service-extensions#135]
A [`Container` provides a `trafficPort`](https://github.com/cdklabs/cdk-ecs-service-extensions/blob/40f6e1abb0d845b107de247c875dea628076e523/src/extensions/container.ts#L31-L34) to allow you to define the port the image listens for traffic on.

However, there are many flavours of container that should not listen on any ports. For example, a service that is polling for SQS queue messages.

Also, some people will want to run services that listen on multiple ports.

The underlying [`ContainerDefinition` provides a `portMapping` property](https://github.com/aws/aws-cdk/blob/d917112487a8f0f1e38d150628b30675f46d8d43/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L332-L336) that has the flexibility to provide no mappings, or many mappings. This [`portMapping` is what the `Container` `trafficPort` sets](https://github.com/cdklabs/cdk-ecs-service-extensions/blob/40f6e1abb0d845b107de247c875dea628076e523/src/extensions/container.ts#L139-L142).

Please consider replacing or augmenting the `trafficPort` property by exposing `portMapping` directly as a property on Container.

**Comment by bvtujo** [comment]
In the future, we plan to add documentation and examples in a separate repo to handle custom cases like this, but in general, we encourage folks to use these interfaces to build their custom logic and container infra however they like. The Extensions aim to be a method and a living repository of community knowledge. 

I'd love to see a community implementation of this, and we'll work on writing an example ourselves.
