### ISSUE TITLE
HttpLoadBalancerExtension should expose targetGroup as a member

### ISSUE THREAD

**Issue by ztrange** [cdklabs/cdk-ecs-service-extensions#209]
Hello.

We are trying to replace a deployment of an application that uses `ApplicationLoadBalancedFargateService` with one made using `@aws-cdk-containers/ecs-service-extensions`. We have been able to configure almost everything but are a little stuck when configuring the health check for the application. Specifically, we are not able to find how to set up the health check path and port.

With our previous deployment we used :
```js
application.targetGroup.configureHealthCheck({
      path: '/ping',
      port: '3000',
      healthyHttpCodes: '200-299',
      interval: Duration.seconds(30),
      timeout: Duration.seconds(5),
      healthyThresholdCount: 5,
      unhealthyThresholdCount: 5,
    });
```

But using service extensions, specifically the `HttpLoadBalancerExtension` there is no straightforward way to access the load balancer instance nor the target group.

We tried using a `ContainerMutatingHook` but werw only able to access the docker native health check, which didn't work for our use case. 

We have a couple more ideas of how to do it but were wondering if there is a recommended way since we understand that ServiceExtensions should allow us to do the same as `ApplicationLoadBalancedFargateService` but having more freedom to configure the infrastructure.

Thanks!

**Comment by bvtujo** [comment]
Thanks so much for bringing this to our attention. There are a number of parameter gaps in the default constructs, and I think we should be exposing the target group on the HttpLoadBalancerExtension. I'll discuss getting this prioritized.
