### ISSUE TITLE
docs: where are docs for FireLens obtainDefaultFluentBitECRImage

### ISSUE THREAD

**Issue by PettitWesley** [cdklabs/cdk-ecs-service-extensions#249]
Hello, apologies if this is a very naive or confused question, but I'm aware that there is a function referenced in this package here: https://github.com/cdklabs/cdk-ecs-service-extensions/blob/main/src/extensions/firelens.ts#L99

Which I think is still housed here: https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-ecs/lib/firelens-log-router.ts#L155

I can't find any documentation for `obtainDefaultFluentBitECRImage`. Where is the documentation for that function? Is it not meant to be used in end-user code?

https://github.com/aws/aws-cdk/issues/7366

**Comment by madeline-k** [comment]
See answer in the linked aws-cdk issue. Sorry this is pretty confusing. We should add this into the AWS CDK library's `ecs` module.
