### ISSUE TITLE
Getting construct references for resources

### ISSUE THREAD

**Issue by Townsheriff** [cdklabs/cdk-ecs-service-extensions#33]
Hey,

This library seems very nice and the api seems very clear. I'm trying to use it and I don't understand how I'm supposed to get internal resources for example load balancer. I need load balancer to add it to cloudfront origin, but the HttpLoadBalancerExtension property loadBalancer is private, I could override the class and extract the load balancer, but that seems an overkill.

What is your suggested way?

Cheers,
Arturs

**Comment by bvtujo** [comment]
Best way currently is to grab the children of your stack, like so: 
```typescript
declare const yourService: Service;

const elb = stack.node.findChild("`{yourService.id}-load-balancer`);
```

Does that solve your problem? This is a typical escape-hatch way of grabbing child resources. Feel free to reopen if you have other questions!
